baseURL = '/'
languageCode = 'en-us'
DefaultContentLanguage = "en"
title = 'Paul Franceschi: Philosophy & Concepts'
theme = "PaperMod"
author = "Paul Franceschi"
copyright = "Copyright © 2019-2023, Paul Franceschi; all rights reserved."

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "paradoxes"
    name = "Paradoxes"
    url = "/paradoxes/"
    weight = 2
  [[menu.main]]
    identifier = "study_of_concepts"
    name = "Study of concepts"
    url = "/study_of_concepts/"
    weight = 3
  [[menu.main]]
    identifier = "psycho_pathological_philosophy"
    name = "Psycho-pathological philosophy"
    url = "/psycho_pathological_philosophy/"
    weight = 4
  [[menu.main]]
    identifier = "ontology"
    name = "Ontology"
    url = "/ontology/"
    weight = 5
  [[menu.main]]
    identifier = "books"
    name = "Books"
    url = "/books/"
    weight = 6  
  [[menu.main]]
    identifier = "courses"
    name = "Courses"
    url = "/courses/"
    weight = 7
  [[menu.main]]
    identifier = "reviews"
    name = "Reviews"
    url = "/reviews/"
    weight = 8  
   [[menu.main]]
    identifier = "en_francais"
    name = "En français"
    url = "/en_francais/"
    weight = 9
   
