baseURL = '/'
languageCode = 'en-us'
title = 'Your New Hugo Site'
theme = "PaperMod"

# home-info mode
homeInfoParams:
  Title: "Hi there \U0001F44B"
  Content: Welcome to my blog

socialIcons:
  - name: twitter
    url: "https://twitter.com/"
  - name: stackoverflow
    url: "https://stackoverflow.com"
  - name: github
    url: "https://github.com/"
