baseURL = '/'
languageCode = 'en-us'
DefaultContentLanguage = "en"
title = 'Paul Franceschi: Philosophy & Concepts'
theme = "PaperMod"
author = "Paul Franceschi"
copyright = "Copyright © 2019-2023, Paul Franceschi; all rights reserved."

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "paradoxes"
    name = "Paradoxes"
    pageRef = "/content/pages/paradoxes.md"
    url = "/paradoxes/"
    weight = 2
  [[menu.main]]
    identifier = "study_of_concepts"
    name = "Study of concepts"
    pageRef = "/content/pages/study_of_concepts.md"
    url = "/study_of_concepts/"
    weight = 3
  [[menu.main]]
    identifier = "psycho_pathological_philosophy"
    name = "Psycho-pathological philosophy"
    pageRef = "/content/pages/psycho_pathological_philosophy.md"
    url = "/psycho_pathological_philosophy/"
    weight = 4
  [[menu.main]]
    identifier = "ontology"
    name = "Ontology"
    pageRef = "/content/pages/ontology.md"
    url = "/ontology/"
    weight = 5
  [[menu.main]]
    identifier = "books"
    name = "Books"
    pageRef = "/content/pages/books.md"
    url = "/books/"
    weight = 6  
  [[menu.main]]
    identifier = "courses"
    name = "Courses"
    pageRef = "/content/pages/courses.md"
    url = "/courses/"
    weight = 7
  [[menu.main]]
    identifier = "reviews"
    name = "Reviews"
    pageRef = "/content/pages/reviews.md"
    url = "/reviews/"
    weight = 8  
   [[menu.main]]
    identifier = "en_francais"
    name = "En français"
    pageRef = "/content/pages/en_francais.md"
    url = "/en_francais/"
    weight = 9

  [[menu.fr]]
    identifier = "home_fr"
    name = "Accueil"
    url = "/fr/"
    weight = 1
  [[menu.fr]]
    identifier = "paradoxes_fr"
    name = "Paradoxes"
    pageRef = "/content/pages/fr/paradoxes.md"
    url = "/fr/paradoxes/"
    weight = 2
  [[menu.fr]]
    identifier = "study_of_concepts_fr"
    name = "Study of concepts"
    pageRef = "/content/pages/fr/study_of_concepts.md"
    url = "/fr/study_of_concepts/"
    weight = 3
  [[menu.fr]]
    identifier = "psycho_pathological_philosophy_fr"
    name = "Psycho-pathological philosophy"
    pageRef = "/content/pages/fr/psycho_pathological_philosophy.md"
    url = "/fr/psycho_pathological_philosophy/"
    weight = 4
  [[menu.fr]]
    identifier = "books_fr"
    name = "Books"
    pageRef = "/content/pages/fr/books.md"
    url = "/fr/books/"
    weight = 6  
  [[menu.fr]]
    identifier = "courses_fr"
    name = "Courses"
    pageRef = "/content/pages/fr/courses.md"
    url = "/fr/courses/"
    weight = 7
   [[menu.fr]]
    identifier = "in_english_fr"
    name = "In english"
    pageRef = "/content/pages/fr/in_english.md"
    url = "/fr/in_english/"
    weight = 9

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
